### PR TITLE
Js2 ca

### PR DESCRIPTION
**Pull request by KennTorg**

### CODE REVIEW

**Review by Fermain — CHANGES_REQUESTED** [review]
Hi, I recorded this a few weeks ago and sent it to your student and personal mail. Have you seen this?

https://www.loom.com/share/4da66500aeed486095c0cd7b3aa49efc

**Comment by KennTorg** [comment]
no i havent seen it. gonna do it now. but i guess i failed. feel like
quitting now

tir. 31. jan. 2023 kl. 08:07 skrev Oliver Dipple ***@***.***>:

**Comment by Fermain** [comment]
If you can get me these changes I can change your grade. Maybe we should talk on Discord?

**Comment by KennTorg** [comment]
Yeah, I can do that.

tir. 31. jan. 2023 kl. 09:06 skrev Oliver Dipple ***@***.***>:

> If you can get me these changes I can change your grade. Maybe we should
> talk on Discord?
>

**Pull request merged**
